### ISSUE TITLE
command line to convert svg to font

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/font#1]
https://github.com/FontCustom/fontcustom

**Comment by lpatiny** [comment]
dnf install gcc mysql-devel ruby-devel rubygems zlib-devel

**Comment by targos** [comment]
you need mysql to create a font ?

**Comment by lpatiny** [comment]
Indeed it does not make sense. I change my comment.

**Comment by lpatiny** [comment]
I was not able to install this project. @targos if you have the opportunity to try on your computer. I have an error when I do the `gem install fontcustom` and could not find a solution on the web.

**Comment by lpatiny** [comment]
Finally we are including directly the SVG but this has as consequence to increase the size of the css by a factor 10 ...
