### ISSUE TITLE
new icon

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/font#11]
We would need an icon similar to the following one in which the 3 spectra are on the same line. (to switch icon between stack and un stack spectra).

![image](https://user-images.githubusercontent.com/1484241/68406814-c4f52d80-0182-11ea-9471-83fc2c97abca.png)

**Comment by djeanner** [comment]
here it is : https://github.com/cheminfo/font/blob/master/svg/nmr/overlay3-aligned.svg
