### ISSUE TITLE
no build and ai files

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/font#12]
@djeanner 

You don't need to push the build. We are building and release package after

Are the SVG correctly editable by AI ? Otherwise could you also save the .ai files so that in case we could reedit later ?

Finally in the commit message could you use the semantic commit message
https://www.conventionalcommits.org/en/v1.0.0/

For new icons it would be:
`feat: new integral icon`

**Comment by djeanner** [comment]
@lpatiny 
Yes, icons are editable with Illustrator, Inkscape.
